version: 1.0.{build}
image: Visual Studio 2022
before_build:
  # Download the latest dotnet-install.ps1 script
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://dot.net/v1/dotnet-install.ps1', "$env:appveyor_build_folder\dotnet-install.ps1")

  # Install .NET 10 SDK
  - ps: '& "$env:appveyor_build_folder\dotnet-install.ps1" -Channel "10.0" -InstallDir "C:\Program Files\dotnet"'

  - ps: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Suave.Minify/bin/Release/*.nupkg
  name: nugets